[package]
name = "pcanwork-ui-features"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
slint = { version = "1.18.0", default-features = false, features = ["std", "compat-1-18", "raw-window-handle-06"] }

[build-dependencies]
slint-build = "1.18.0"

[dev-dependencies]
slint = { version = "1.18.0", default-features = false, features = ["std", "compat-1-18", "renderer-software"] }
i-slint-core = { version = "=1.18.0", features = ["image-decoders", "svg"] }
